### ISSUE TITLE
Include buildings (linestrings) for housenumbers

### ISSUE THREAD

**Issue by philippks** [OSMNames/OSMNames#100]
Until now only housenumbers as nodes have been imported with imposm (see [here](https://github.com/OSMNames/OSMNames/blob/607ef0ad9bdd68e7805d26b7fff54dbddfc33d7e/data/import/mapping.yml#L156)). Even more important are housenumbers as linestrings.

**Comment by klokan** [comment]
We are getting more and more into what is OpenMapTiles doing already.

**Comment by sfkeller** [comment]
OpenMapTiles is about base map creation potentially up to hourly updates. 
OSMNames is about housenumber/POI and hierarchy extraction, aggregation (incl. associated street relations) and cleansing. And hourly updates are no use case yet. 
I very much support OpenMapTiles, but I would not like to get too much dependencies nor merge the projects according to the Unix philosophy "to write programs that do one thing and do it well".
