### ISSUE TITLE
Consider switch to Solr as sample search server

### ISSUE THREAD

**Issue by EamonKeane** [OSMNames/OSMNames#125]
Great work putting together this project. A great practical use of this data is to geocode for purposes of navigation and route optimisation. For this, the centre of a given street is often sufficient. 

The input, however, is often messy, with abbreviations, mis-spellings especially when this comes to ecommerce delivery. In addition, the hierarchy in OSM is often not how people write addresses in real-life, so a fuzzy search is essential.

The best use case for this data I think is finding the centre of the 17m 'highway' classes. On the basis that most roads are in OSM, this is a reasonable alternative to expensive proprietary datasets mostly under lock and key by the respective postal agencies. Google in my experience generally doesn't do a great job of finding relevant results for this messy input data.

While I'm not intimately familiar with SphinxSearch, it doesn't appear to be the most active search server. After testing Solr and Elasticsearch, I think Solr is easily the best because it implements features of the underlying Lucene which are relevant to autocomplete and search which Elasticsearch does not (such as BlendedInfixLookupFactory).

Take as an example if searching for 'Rue Linois, Paris, France'. This comes up first when searching for 'Rue Linois, Paris, France' on OSM names. If just one letter is changed to 'Rue linos, paris, france', sphinx gives an irrelevant result - 'Rue des Longs'. Both Google and Solr's default setting still give the correct result.

I'm adding this issue as a place to discuss whether a different default provider for OSM-names is worth considering?

**Comment by sfkeller** [comment]
Thank you very much for your input. It's important realize that this project is mainly about the generation of a dataset ready for geocoding (as geonames gazetter and now also as fine grained geocoder at housnumber level). As you say, SphinxSeach is just the backbone of a show case available under osmnames.org. So, I'm closing this issue here. Can you pls. re-enter it over at https://github.com/OSMNames/www.osmnames.org/issues ?

**Comment by EamonKeane** [comment]
Thanks, will do!

**Comment by klokan** [comment]
An implementation of an alternative search engine for OSMNames data in Solr / Elasticsearch / Lucene is very welcome...

Please create a new project on GitHub and paste here a link - so people can try this new alternative.

We would be very keen on comparing the performance, required hardware resources and quality of the search results with existing SphinxSearch implementation...

Everybody in the community benefits if there are more implementation and choice of different open-source software - so go a head and implement the first version... ;-)

The project is intentionally switching the data preprocessing and generating part from the search engine - to encourage alternative implementations of software for using the OSM gazetteer data.
