### ISSUE TITLE
Update readme link for data format

### ISSUE THREAD

**Issue by MartinMikita** [OSMNames/OSMNames#128]
Link is broken - https://github.com/OSMNames/OSMNames#data-format-of-tsv-export-of-osmnames

**Comment by philippks** [comment]
Hi @MartinMikita 

Thank you for the hint. The link points now to the offical documentation. As soon as the newest Read The Docs Build will be started (maybe by you?), the documentation will contain the section about the output format.

**Comment by MartinMikita** [comment]
Documentation rebuild, thanks!

**Comment by philippks** [comment]
Great, thank you!
