### ISSUE TITLE
Review appending postcodes to entries

### ISSUE THREAD

**Issue by EamonKeane** [OSMNames/OSMNames#129]
I'm attempting to use osmnames for geocoding unstructured data for route optimisation purposes. By unstructured data, I mean that the data is captured in free-form by an e.g online retailer before being handed over to a delivery company. 

The first line of the address could contain the street or it could contain a person's name. I don't believe Libpostal is trained to recognise first names/company names, so is of little use to normalise. 

Hence my current approach is to do full text search and use the result from OSM names with the highest score. The postcode is generally present in the input address, which is a great way to shrink the search area and sanity check the result.

In my initial testing of OSM names, it appears easy enough for an input string to match a street in a different part of e.g. Germany or Spain as they have very repetitive street names. Geocoding with the postcode, however, would have given the right result.

As discussed in the thread here (https://github.com/OSMNames/OSMNames/issues/97), I understand that OSM has limited postcode information, so relying on this will not give good postcode coverage for OSMNames.

Given this, has there been any consideration to appending in postcode information from a different source? For example, whosonfirst (https://whosonfirst.mapzen.com/spelunker/placetypes/postalcode/) have approximate postcode polygons for a lot of countries.

The quality of these vary depending on country. In most cases the official versions of postcode polygons are maintained by the national postal operator and are not open source. However it is possible to reconstruct them from open data using Voronoi or clustering.

For the UK this has been done here:
http://www.opendoorlogistics.com/data/
https://gis.stackexchange.com/questions/43337/uk-postcode-district-aggregation

For the Netherlands, it has been done here:
https://github.com/whosonfirst-data/whosonfirst-data-postalcode-nl

I appreciate it would be a big/messy task to consider appending these onto the OSM data, however if the goal is for OSMNames to be used as a standalone geocoder, it would greatly increase its value.

Is using data not currently in OSM beyond the scope of this project? Would it be worth adding the postcodes from Whosonfirst to the dataset if the street is in a postcode polygon?

**Comment by sfkeller** [comment]
I'm of course also interested in a valuable data product, but our resources are limited (contributors are welcome!). 

I think we have to focus on OSM data, first, because of the complexity of the data extraction task, and second, because of licensing reasons. 

So for example we're considering Wikidata as a single external source to complement the geonames with exonyms; there the relationship (wikidata tag), the attribute ("name") and the license are clear.

In case of postcodes it's a mess as you say: The sources are so diverse and the license is unclear (or even incompatible). This includes also Whosonfirst.

**Comment by EamonKeane** [comment]
Thanks for your thoughts, not sure I'll have the time/skill to be a contributor but I'll think about it. 
Openaddresses could be a reasonable bet for some countries, e.g. if everything in the osmnames street bounding box on OA has the same postcode, then append that.

**Comment by sfkeller** [comment]
Related to #191 so closing.
