### ISSUE TITLE
Bad request on non-latin searches

### ISSUE THREAD

**Issue by SantiagoHorcajo** [OSMNames/OSMNames#139]
Hi,
I've problems when I try to search a non-latin string, in that cases OSMNames answer "400 Bad Request"
For example searching Beijing in Chinese:  北京市
Thanks a lot in advance

![non latin](https://user-images.githubusercontent.com/10306215/30735130-2a7fc28c-9f7e-11e7-875a-4149c790113c.jpg)

**Comment by philippks** [comment]
hi @SantiagoHorcajo, thanks for your feedback.

The search actually has its own repository, where already an issue for the described problem exists: https://github.com/klokantech/osmnames-sphinxsearch/issues/38

So I'll close this one.
