### ISSUE TITLE
Adding missing street names to housenumber

### ISSUE THREAD

**Issue by sfkeller** [OSMNames/OSMNames#14]
In OSM often addresses lack streetname. These missing streetnames can be added when searching for closest street to the housenumber coordinate (which is inside sam admin. boundary). See also "Addresses" at http://tools.geofabrik.de/osmi/ and Lukas T.'s work.

**Comment by klokan** [comment]
+1

Export of LonLat for every house number, with a correct street name (or complete address and zip) should be done in a separate TSV format - then existing export.
