### ISSUE TITLE
Release filesize dropped from v2.0.1 to v2.0.2

### ISSUE THREAD

**Issue by chris-lu** [OSMNames/OSMNames#142]
It seems the release file planet-latest_geonames.tsv.gz v2.0.2 is missing some of data. I generated the file on my own, leading to an extra 200MB (1702521475 Bytes, instead of 1521636287), which is closer to the previous data files. 
I can provide the generated file if needed.
What do you think ?

**Comment by philippks** [comment]
Hi @chris-lu 

It would be great if you can provide your generated data. I'll have a look.

Thank you very much for your effort.

**Comment by chris-lu** [comment]
Here it is: https://drive.google.com/file/d/0B8I6_0pYbOB3dndmemRVRklKNmc/view

**Comment by klokan** [comment]
Sorting by rank and gzip compression can make a significant difference in size.

Could you please count the lines?

If there are any missing data - we need to identify the type of missing features.

**Comment by chris-lu** [comment]
Release 2.0.2:  23.477.033 lines
My File: 23.529.879 lines
So "only" 52.846 lines are different. 

I was digging into this because some big cities (ie. Brussels, Marrakesh, etc.)  where not exported as class:place,type:city but I realize it's not related as I start to enter into the code. 

I guess the small difference may be due to the date difference the file was generated.
Sorry for the inconvenience, I guess this request may be closed.

**Comment by philippks** [comment]
thanks for checking @chris-lu 
2.0.3 will be released shortly, so I'll close this issue.
