### ISSUE TITLE
Reduce precision of longitude / latitude

### ISSUE THREAD

**Issue by philippks** [OSMNames/OSMNames#146]
Right now the longitudes and latitudes are rounded to 7 decimal places. I propose to reduce the precision to 5 decimal places, which should be sufficient: https://en.wikipedia.org/wiki/Decimal_degrees

this would reduce the file size, at least a little bit...

**Comment by klokan** [comment]
Not sure if this is really required

**Comment by m-mohr** [comment]
I think it is not necessary to reduce the file size and won't have a huge impact, but a precision of 7 is not needed. 6 or maybe 5 decimal places sounds reasonable.
