### ISSUE TITLE
Hamburg

### ISSUE THREAD

**Issue by m-mohr** [OSMNames/OSMNames#149]
I am not sure whether the OSM data is wrong, but if I search for Hamburg on osmnames.org there are basically two entries: the state and the admin borders.
Th bbox of the state is a point ("boundingbox": [ 10.009913, 53.543762, 10.009913, 53.543762 ]) and the admin borders seem too big. It even covers Bremerhaven, which is far outside of Hamburgs borders. The same bbox can be found for "Hamburg-Mitte", which is wrong.

**Comment by sfkeller** [comment]
I think you suggestion is right: the OSM data is the source of your observations: 
See http://www.openstreetmap.org/relation/62782#map=9/53.7126/9.2153
