### ISSUE TITLE
Type administrative vs city

### ISSUE THREAD

**Issue by klokan** [OSMNames/OSMNames#152]
In this moment the search results for large cities which also happen to be administrative units returns twice the type "administrative". User can't distinguish what to choose then - and it feels like a bug.

For example "Bern", "Basel", "Praha", etc.

It should once have a type "administrative" (the canton) and once type "city".

Zurich and Berlin got it right BTW

Partly related to binding the relation and the linked node - as in Washington D.C. #150

**Comment by philippks** [comment]
fixed with [release v.2.1](https://github.com/OSMNames/OSMNames/releases/tag/v2.1.0)
