### ISSUE TITLE
Amsterdam is in France

### ISSUE THREAD

**Issue by klokan** [OSMNames/OSMNames#153]
See: http://osmnames.org/#q=amsterdam

> Dear Sir or Madam, recently, i found your osmnames.org project in the internet. I wanted to thank you for that project, it helps me a lot. Jet, I might have found a little problem in it. I looked for Amsterdam in your database. And found it with the osm_id... Yet the country_code is france, which must be a mistake. Is there any chance, that could fixe that? sincerely, Erik Radisch

> I forgot the geoname-ID in my previous email: 271110

Reported by: <erik.radisch@uni-passau.de>

**Comment by philippks** [comment]
The whole Netherlands are actually "part of France" 💩

Just a short investigation:

The problem is, that [the relation 47796](http://www.openstreetmap.org/relation/47796) only has the admin_level 3. Since its geometrical center seems to be in France and the admin_level is lower, France is determined as parent.

But in OpenStreetMap the [the relation 47796](http://www.openstreetmap.org/relation/47796) is linked to the [relation 2323309](http://www.openstreetmap.org/relation/2323309) as subarea (which has the admin_level 2). If we consider this attribute [when determining linked places](https://github.com/OSMNames/OSMNames/blob/master/osmnames/prepare_data/determine_linked_places.sql), the problem should be solved.

**Comment by sfkeller** [comment]
At least this particular issue could be solved, when - instead of ST_Centroid the admin_centre would be taken if it exists. In this case it's the Node Amsterdam (268396336) as part of this relation http://www.openstreetmap.org/relation/47796 .

**Comment by Johanneke** [comment]
We are trying to setup an app where we need to lookup countries and continents based on latitude/longitude and I just ran into this issue (Netherlands being part of France) as well. Do you know if this issue exists for other area's? We can't use this if we can't determine country/continent correctly...

**Comment by klokan** [comment]
@Johanneke these problems were not present in the original data release.
Download TSV from https://github.com/OSMNames/OSMNames/releases/tag/v1.1

Version 2 has a lot of improvements - but unfortunately a lot of bugs too - despite 3 bug fix releases there are still critical bugs introduced as students at HSR have been adding new functionality to the data generator.

@philippks @sfkeller is there one more fix release planned anytime soon?
Bugs like this one are embarrassing.

**Comment by philippks** [comment]
@klokan you're right, these are terrible bugs.

I believe most critical was a change in the creation of the hierarchy due to better performance and special cases. Unfortunately it did break the quality in some cases.

I have almost no time to invest at the moment but I did a quick revert about this change and am running a new export. Could you @klokan or @MartinMikita review the newest export when it is finished? It should fix this issue and #155 as well.

I can't offer much more right now...

**Comment by MartinMikita** [comment]
Yes, prepare the draft release, and we will review the changes on our side.

**Comment by klokan** [comment]
Thank you very much @philippks! We are ready to dig into this on our side too...

**Comment by Johanneke** [comment]
Do you know what the ETA on the new release is? The 1.1 version results in a bunch of errors in the klokantech/osmnames-sphinxsearch docker container :-(

**Comment by philippks** [comment]
@Johanneke I'll upload the new export the next hour. After a review of @MartinMikita it hopefully can be released.

**Comment by MartinMikita** [comment]
@Johanneke If you want to use OSMNames release 1.1, you need to use older version of osmnames-sphinxsearch, for example the latest supported for OSMNames 1.1 is [1.4](https://github.com/klokantech/osmnames-sphinxsearch/releases/tag/v1.4) with docker image `klokantech/osmnames-sphinxsearch:1.4`

**Comment by Johanneke** [comment]
Thank you so much!

**Comment by philippks** [comment]
@MartinMikita I uploaded the newest geonames.tsv.gz and created a pre-release v2.0.4. (the housenumbers will follow). Could you have a look?

**Comment by MartinMikita** [comment]
Thanks a lot, @philippks! We are now indexing this data already, we should know something more in about 1 hour.

**Comment by MartinMikita** [comment]
```

    {
      "wikipedia": "nl:Amsterdam",
      "rank": 20026478.0,
      "county": "",
      "street": "",
      "wikidata": "Q727",
      "country_code": "nl",
      "osm_id": "271110",
      "housenumbers": "",
      "id": 123,
      "city": "Amsterdam",
      "display_name": "Amsterdam, Amsterdam, North Holland, Netherlands",
      "lon": 4.897975,
      "state": "Netherlands",
      "boundingbox": [
        4.729242,
        52.278175,
        5.079162,
        52.431065
      ],
      "type": "administrative",
      "importance": 0.749677,
      "lat": 52.374538,
      "class": "boundary",
      "name": "Amsterdam",
      "country": "The Netherlands",
      "name_suffix": "NL",
      "osm_type": "relation",
      "place_rank": 20.0,
      "alternative_names": ""
    },
```

Same goes for #155 :+1:

**Comment by MartinMikita** [comment]
@philippks 

We are satisfied with the fixed version now.
Please, could you push your changes for 2.0.4 and make a proper release?
We have required geonames.tsv.gz file downloaded, so you can delete the release, or rename it to `v2.0.3.1`, to keep the file there.

After you push the changes, this ticket and #155 can be closed.
Thanks again for your fast help!

**Comment by philippks** [comment]
thank you for the fast review and import @MartinMikita 
release v2.0.4 is now published.

**Comment by beardhatcode** [comment]
This issue popped up again. Amsterdam is in France again

```
Amsterdam	""	relation	271110	boundary	administrative	4.8979755	52.37454020	0.749676919753327	""	Amsterdam	Metropoolregio Amsterdam	Nederland	France	fr	Amsterdam, Centrum, Amsterdam, Metropoolregio Amsterdam, Stadsregio Amsterdam, Noord-Holland, Nederland, France	4.7292417	52.2781741	5.0791621	52.4310637	Q727	nl:Amsterdam	""
```

**Comment by philippks** [comment]
@beardhatcode this is strange, since nothing changed for a long time... which files did you process to get this line?

**Comment by beardhatcode** [comment]
The one from the website [v2.04](https://github.com/OSMNames/OSMNames/releases/download/v2.0.4/planet-latest_geonames.tsv.gz). 

I just tried it again with 2.1.1 and with 2.0.4 and it seems fine now. I don't know what happend. (I probably did something wrong)
