### ISSUE TITLE
Empty importance field

### ISSUE THREAD

**Issue by MartinMikita** [OSMNames/OSMNames#154]
There are last 4642 rows from the v2.0.3 planet with an empty `importance` field.
These entries should have number `0.0`, but should never be empty!

**Comment by philippks** [comment]
@MartinMikita I just uploaded the newest export to release [v2.0.5](https://github.com/OSMNames/OSMNames/releases/tag/v2.0.5). It covers two small fixes. Could you've a look if you find some time?
