### ISSUE TITLE
cookham rise is not in lancashire

### ISSUE THREAD

**Issue by komodo-solutions** [OSMNames/OSMNames#155]
making a reverse geocoding request for lon=-0.7203719, lat=51.568788899999994 returns the correct place but not the correct county/area.
It returns
`{"count": 1, "previousIndex": 0, "startIndex": 1, "totalResults": 1, "results": [{"wikipedia": "", "rank": 0, "county": "Lancashire", "street": "", "wikidata": "", "country_code": "gb", "osm_id": "257628509", "housenumbers": "", "id": 1954691, "city": "Lancaster", "display_name": "Cookham Rise, Great Britain, Lancaster, Lancashire, North West England, England, United Kingdom", "lon": -0.726412, "state": "England", "boundingbox": [-0.726412, 51.557114, -0.726412, 51.557114], "type": "village", "importance": 0.275, "lat": 51.557114, "class": "place", "distance": 1364.998535, "name": "Cookham Rise", "country": "United Kingdom", "name_suffix": "", "osm_type": "node", "place_rank": 19.0, "alternative_names": ""}]}`
but instead it should refer to Windsor & Maidenhead

**Comment by komodo-solutions** [comment]
Neither is Hackwood in Hampshire...also showing Lancashire

**Comment by philippks** [comment]
Thank you for the report @komodo-solutions 

The creation of the hierarchy needs some love, fore sure.

Some notes about the problem:
* The hierarchy is created, based on the place_rank (polygons with higher place_ranks are considered first).
* The place_rank of the island Great Britain is 17 (which is even higher then Lancshire), why it is set as "first parent"
* Windsor and Maidenhead has the place_rank 12.

It looks like the geometry needs to be considered more strictly for the hierarchy....

**Comment by komodo-solutions** [comment]
Definately! A place /must/ be within the polygon bounds of the higher 
administrative region, otherwise it is just wrong...

**Comment by komodo-solutions** [comment]
Hi @philippks just wondering if there is an eta for getting this corrected? It's kind of critical since I'm putting out a new app which relies on this data, and a new app simply has to be accurate.
It did use to show correctly, a while back when I was first developing, so not sure what has happened!

**Comment by MartinMikita** [comment]
Thanks to @philippks it was fixed, and we are going to publish this release in probably 2 hours on the production.

**Comment by komodo-solutions** [comment]
Fantastic news, thank you!

**Comment by MartinMikita** [comment]
@komodo-solutions It is deployed now, but there is some cached responses, they should be rotated in 24 hours.

**Comment by philippks** [comment]
release v2.0.4 is now published

**Comment by komodo-solutions** [comment]
This issue appears to have resurfaced!! Please can it be looked at as a matter of urgency?

**Comment by MartinMikita** [comment]
We have modified the API server and it loaded an older version of OSMNames, accidentally.
It was fixed and cache was purged.

Sorry for the inconvenience.
