### ISSUE TITLE
Improve hierarchy with per country rules

### ISSUE THREAD

**Issue by klokan** [OSMNames/OSMNames#158]
OpenStreetMap has for each country recorded different set of `admin_level` values.

The libpostal project collected this "per country" rules and have them available here:

https://github.com/openvenues/libpostal/tree/master/resources/boundaries/osm

We could probably use these to display a more meaningful display_name or reconstruct in a better way the hierarchy from OpenStreetMap.

**Comment by philippks** [comment]
with release v2.1 the mapping of libpostal will be imported and used to update all polygon types which have the type = 'administrative'. This will also solve #152.
