### ISSUE TITLE
Autocomplete isn't bringing up results for postcodes when filtered by country

### ISSUE THREAD

**Issue by nicholasgriffintn** [OSMNames/OSMNames#159]
I want to be able to filter autocomplete results to come only from the UK while being able to run a postcode search, I have managed to filter it to only UK results, however, now postcode search doesn't work (it does work when the results aren't filtered).

Here's my code:

showFilterContent += "<div id=\"txtLocationWrapper\" class='vf-col-xs-12'>" +
            '<input autocomplete="off" id="txtLocation" type="text" placeholder="Find a place..." role="combobox" aria-autocomplete="list" class="" aria-haspopup="false" aria-expanded="false"/>' +
            '<script>' +
            'var autocomplete = new kt.OsmNamesAutocomplete(' +
            "'txtLocation', 'https://search.osmnames.org/', '');" +
            'autocomplete.registerCallback(function(Mapitem) {' +
            "$lat = Mapitem.lat;" +
            "$lon = Mapitem.lon;" +
            "jQuery('#VF_insert_jobs').html('');" +
            "ixAd = 0;" +
            "blockUI();" +
            "getView();" +
            "jQuery('.location-API-data').html((JSON.stringify(Mapitem, ' ', 2)));" +
            '});' +
            '</script>' +

Also here's a screen of the implementation and the search:

![screen shot 2018-01-25 at 19 35 27](https://user-images.githubusercontent.com/12116098/35408732-14a34d20-0208-11e8-888e-47026e797b16.jpg)

**Comment by sfkeller** [comment]
This repo is about the data (files) extraction from OSM. I think your issue fits better over at https://github.com/OSMNames/www.osmnames.org/issues .

**Comment by nicholasgriffintn** [comment]
You want me to put an issue with the API in the GItHub for the website? Erm okay, seems a little backwards but sure lol.

**Comment by MartinMikita** [comment]
Your issue should be posted in the search engine used on the web - https://github.com/klokantech/osmnames-sphinxsearch

Please, submit this ticket there.
