### ISSUE TITLE
BBox for continents consists of just a single point

### ISSUE THREAD

**Issue by SirkoS** [OSMNames/OSMNames#161]
The bounding boxes for continents are currently set to basically points (see below example for Afrika). I think giving a single point as is misleading especially in automated processing.

PS: I don't see any boundary information present in OSM itself either. 

```
{
  "wikipedia": "en:Africa",
  "osm_id": "36966057",
  "display_name": "Africa",
  "...": "...",
  "lon": 16,
  "boundingbox": [
    16,
    2,
    16,
    2
  ],
  "type": "continent",
  "lat": 2,
  "...": "..."
}
```

**Comment by sfkeller** [comment]
Hi Sirko, Thanks for reporting. As you already noticed, in OSM the places of type continent are "officially" tagged as a node: https://wiki.openstreetmap.org/wiki/Tag:place%3Dcontinent

You may have expected boundaries. These are often broken in OSM but nevertheless available after quite some preprocessing: see http://openstreetmapdata.com/. 

There is an alternative source for boundaries from http://www.naturalearthdata.com/ (public domain).

Feel free to make a pull request and contribut further to this project OSMNames :-). I'm also ready to reopen this issue.
