### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by tdierickx** [OSMNames/OSMNames#163]
Hopefully, this helps somebody else out there. I kept getting errors running the following:

`docker-compose run --rm osmnames`

It would generate the following:

> can't load package: package github.com/omniscale/imposm3/cmd/imposm3: cannot find package "github.com/omniscale/imposm3/cmd/imposm3" in any of:
        /usr/local/go/src/github.com/omniscale/imposm3/cmd/imposm3 (from $GOROOT)
        /go/src/github.com/omniscale/imposm3/cmd/imposm3 (from $GOPATH)
ERROR: Service 'osmnames' failed to build: The command '/bin/sh -c go get github.com/omniscale/imposm3  && go install github.com/omniscale/imposm3/cmd/imposm3' returned a non-zero code: 1

Changing the following line in the Dockerfile from

`RUN go get github.com/omniscale/imposm3 \
 && go install github.com/omniscale/imposm3/cmd/imposm3`

to

`RUN go get github.com/omniscale/imposm3 \
 && go install github.com/omniscale/imposm3/cmd/imposm`

appears to have fixed my issue - atleast in terms of the container atleast building without error. I still don't get an exported .tsv data file built, but that's another story...

**Comment by MartinMikita** [comment]
Hi,

Thanks for your report, the command `imposm3` was renamed into `imposm` a day ago, see https://github.com/omniscale/imposm3/commit/0ca34413d692afb44f49b8715ef6e9423a78fe86

You can create a pull request to fix this change in Dockerfile, and we will merge it. This change will be linked to your GitHub account as a contributor.

**Comment by tdierickx** [comment]
Thanks Martin. 

As a follow-up and on a related note, I also needed to edit "osmnames/import_osm/import_osm.py" to resolve the following error:

> OSError: [Errno 2] No such file or directory

**_before_**:
```
check_call([
	"imposm3", "import",
	"-connection", imposm_connection,
	"-mapping", "{}/mapping.yml".format(settings.get("IMPORT_DIR")),
	"-dbschema-import", settings.get("DB_SCHEMA"),
	"-read", pbf_filepath,
	"-write",
	"-overwritecache",
])
```

**_after_**:
```
check_call([
	"imposm", "import",
	"-connection", imposm_connection,
	"-mapping", "{}/mapping.yml".format(settings.get("IMPORT_DIR")),
	"-dbschema-import", settings.get("DB_SCHEMA"),
	"-read", pbf_filepath,
	"-write",
	"-overwritecache",
])
```

Now, I have output files in the "data/export" folder! Woot!

**Comment by MartinMikita** [comment]
Hi, do you want to create a pull request with these your fixes? Or should we create it and address you as a contributor?

**Comment by tdierickx** [comment]
You can go ahead and address it / no need to worry about naming me as a contributer
