### ISSUE TITLE
All towns in Northern Ireland are marked as being in IE instead of GB, wrong city as well

### ISSUE THREAD

**Issue by chris-lu** [OSMNames/OSMNames#171]
Hello OSMNames team !

I found out that in the OSMNames website (and in the OSMNames data) all towns and villages located in Northern Ireland  (still part of GB for now ;) ) are marked as being part of Ireland and having country code IE.
City are all set to Ireland which is likely wrong as well.
Country should be "Northern Ireland", country_code should be "gb" and "city" should not be "Ireland"

Is this error part of OSMNames or maybe from OpenStreetMap data itself, or an anticipation from a upcoming Brexit event ?

Example for Dungiven in Northern Ireland: 
`{
  "wikipedia": "",
  "rank": 8250218.5,
  "county": "",
  "street": "",
  "wikidata": "Q1265794",
  "country_code": "ie",
  "osm_id": "267763125",
  "housenumbers": "",
  "id": 1294263,
  "city": "Ireland",
  "display_name": "Dungiven, Ireland",
  "lon": -6.924162,
  "state": "",
  "boundingbox": [
    -6.924162,
    54.927238,
    -6.924162,
    54.927238
  ],
  "type": "town",
  "importance": 0.3,
  "lat": 54.927238,
  "class": "place",
  "name": "Dungiven",
  "country": "Ireland",
  "name_suffix": "Ireland, IE",
  "osm_type": "node",
  "place_rank": 18,
  "alternative_names": ""
}`

**Comment by chris-lu** [comment]
I'm giving a try updating prepare_data\create_hierarchy\set_parent_ids.sql

```diff
--- a/osmnames/prepare_data/create_hierarchy/set_parent_ids.sql
+++ b/osmnames/prepare_data/create_hierarchy/set_parent_ids.sql
@@ -27,7 +27,7 @@ DO $$
 BEGIN
   PERFORM set_parent_id_for_elements_within_geometry(id, place_rank, geometry)
           FROM osm_polygon
-          WHERE place_rank <= 22 AND type NOT IN ('water', 'desert', 'bay', 'reservoir')
+          WHERE place_rank <= 22 AND type NOT IN ('water','desert','island','bay','river','peak','volcano','islet','mountain_pass','hill','reservoir','stream')
           ORDER BY place_rank DESC;
 END
 $$ LANGUAGE plpgsql;
```
(values taken from set_place_ranks.sql)

Will take a bit of time to try.

**Comment by chris-lu** [comment]
I found some other location impacted (I guess many islands could be impacted):
Sri Lanka, South of new Zealand, Iceland (Please, tell me if you need specific data as examples.)
I think there are two different kind of data in set_place_ranks.sql : Administrative and geographical. Place ranks there may enter into conflicts, having some geographical linked to administrative and vice-versa (but it may have been made on purpose)

**Comment by philippks** [comment]
hey @chris-lu  you're right. the hierarchy is currently built with a mix of geographical and administrative polygons. I think with the osm data this is currently the best way to go.

But including the geographical island does not make sense it most situations, since mostly a corresponding administrative element exists too. For example with sylt: 
geographical: https://www.openstreetmap.org/relation/1576925
administrative: https://www.openstreetmap.org/relation/1147134 and https://www.openstreetmap.org/relation/1428696

With release v2.1 islands without admin_levels are not taken into account as possible parents when creating the hierarchy.

thanks for your inputs @chris-lu

**Comment by philippks** [comment]
fixed with [release v.2.1](https://github.com/OSMNames/OSMNames/releases/tag/v2.1.0)
