### ISSUE TITLE
Error on docker build — Cannot uninstall 'psycopg2'

### ISSUE THREAD

**Issue by andreydayen** [OSMNames/OSMNames#175]
Hi!

I'm facing the error composing docker image on fresh Ubuntu 18.04 Server with only docker, docker-compose and docker.io installed:
Cannot uninstall 'psycopg2'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Full log:
Step 10/11 : RUN pip install -r requirements.txt.lock
 ---> Running in 333bab2023b8
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting atomicwrites==1.2.1 (from -r requirements.txt.lock (line 1))
  Downloading https://files.pythonhosted.org/packages/3a/9a/9d878f8d885706e2530402de6417141129a943802c084238914fa6798d97/atomicwrites-1.2.1-py2.py3-none-any.whl
Collecting attrs==18.2.0 (from -r requirements.txt.lock (line 2))
  Downloading https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Requirement already satisfied: bzr==2.8.0.dev1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt.lock (line 3)) (2.8.0.dev1)
Requirement already satisfied: configobj==5.0.6 in /usr/lib/python2.7/dist-packages (from -r requirements.txt.lock (line 4)) (5.0.6)
Collecting funcsigs==1.0.2 (from -r requirements.txt.lock (line 5))
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting GeoAlchemy2==0.5.0 (from -r requirements.txt.lock (line 6))
  Downloading https://files.pythonhosted.org/packages/5b/e2/09f9a4c17cf85f142421384550481c34571da594a49368660f26e53318e5/GeoAlchemy2-0.5.0-py2.py3-none-any.whl
Collecting lazy-property==0.0.1 (from -r requirements.txt.lock (line 7))
  Downloading https://files.pythonhosted.org/packages/4f/87/871a1522823d2bba3e8fd8cdea0f5eb7fa7596889f1ed73167d895127046/lazy_property-0.0.1-py2.py3-none-any.whl
Requirement already satisfied: mercurial==4.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt.lock (line 8)) (4.0)
Collecting more-itertools==5.0.0 (from -r requirements.txt.lock (line 9))
  Downloading https://files.pythonhosted.org/packages/2f/9d/dcfe59e213093695f108508af1214cf9cd95cc5489e46877ec5cb56369e5/more_itertools-5.0.0-py2-none-any.whl (52kB)
Collecting pathlib2==2.3.3 (from -r requirements.txt.lock (line 10))
  Downloading https://files.pythonhosted.org/packages/2a/46/c696dcf1c7aad917b39b875acdc5451975e3a9b4890dca8329983201c97a/pathlib2-2.3.3-py2.py3-none-any.whl
Collecting pluggy==0.8.0 (from -r requirements.txt.lock (line 11))
  Downloading https://files.pythonhosted.org/packages/1c/e7/017c262070af41fe251401cb0d0e1b7c38f656da634cd0c15604f1f30864/pluggy-0.8.0-py2.py3-none-any.whl
Collecting psycopg2==2.7.5 (from -r requirements.txt.lock (line 12))
  Downloading https://files.pythonhosted.org/packages/7c/e6/d5161798a5e8900f24216cb730f2c2be5e4758a80d35c8588306831c0c99/psycopg2-2.7.5-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
Collecting py==1.7.0 (from -r requirements.txt.lock (line 13))
  Downloading https://files.pythonhosted.org/packages/3e/c7/3da685ef117d42ac8d71af525208759742dd235f8094221fdaafcd3dba8f/py-1.7.0-py2.py3-none-any.whl (83kB)
Collecting pytest==4.0.2 (from -r requirements.txt.lock (line 14))
  Downloading https://files.pythonhosted.org/packages/19/80/1ac71d332302a89e8637456062186bf397abc5a5b663c1919b73f4d68b1b/pytest-4.0.2-py2.py3-none-any.whl (217kB)
Collecting scandir==1.9.0 (from -r requirements.txt.lock (line 15))
  Downloading https://files.pythonhosted.org/packages/16/2a/557af1181e6b4e30254d5a6163b18f5053791ca66e251e77ab08887e8fe3/scandir-1.9.0.tar.gz
Collecting simple-settings==0.13.0 (from -r requirements.txt.lock (line 16))
  Downloading https://files.pythonhosted.org/packages/d7/15/e4d340392577d2ad53396aca76990d95c25878f859c4b509094128bb2873/simple_settings-0.13.0-py2.py3-none-any.whl
Requirement already satisfied: six==1.10.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt.lock (line 17)) (1.10.0)
Collecting SQLAlchemy==1.2.15 (from -r requirements.txt.lock (line 18))
  Downloading https://files.pythonhosted.org/packages/0c/7d/769c5fc22c0cdefd097b91cc525b6d8c88bf2afd8b0315b1e7ca088956b4/SQLAlchemy-1.2.15.tar.gz (5.6MB)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from pytest==4.0.2->-r requirements.txt.lock (line 14)) (40.8.0)
Installing collected packages: atomicwrites, attrs, funcsigs, SQLAlchemy, GeoAlchemy2, lazy-property, more-itertools, scandir, pathlib2, pluggy, psycopg2, py, pytest, simple-settings
  Running setup.py install for SQLAlchemy: started
    Running setup.py install for SQLAlchemy: finished with status 'done'
  Running setup.py install for scandir: started
    Running setup.py install for scandir: finished with status 'done'
  Found existing installation: psycopg2 2.7.6.1
Cannot uninstall 'psycopg2'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
ERROR: Service 'osmnames' failed to build: The command '/bin/sh -c pip install -r requirements.txt.lock' returned a non-zero code: 1

**Comment by philippks** [comment]
thanks for your feedback. I fixed the issue by changing to python3. Hope everything works now for you.
