### ISSUE TITLE
Trouble importing tsv file

### ISSUE THREAD

**Issue by chapmanjacobd** [OSMNames/OSMNames#177]
I used release 2.0.4 and 2.0.5 of osmnames and both psql / postgres 10.7 and psql / postgres version 11.

I tested it with this command:
`cat planet-latest_geonames.tsv | sed -e 's/\r/ /g' | gawk -F"\t" -v OFS='\t' 'NR > 1 && NF != 24 { print NR "\t" NF "\t" $0; }'`
and there was no output so it should be a complete file yeah?

```
test=# \copy osmnames from '/home/xk/Downloads/planet-latest_geonames.tsv' DELIMITER E'\t';
ERROR:  missing data for column "housenumbers"
CONTEXT:  COPY osmnames, line 296500: "\                way     198111246       natural water   -94.3798827     32.8424510      16      0.35                    Marion County   Texas   United States of..."
```

I tried importing it using DBeaver and R.

In R fread crashes.

In DBeaver (osmnames version 2.0.4):

`SQL Error: Expected separator at line and position: 67340 26: "городской округ Муром",""городской округ ""Округ Муром"""","relation","389675","boundary","administrative","42.0190832","55.5671012","12","0.45","","","городской округ Муром","Central Federal District","Russia","ru","городской округ Муром, Vladimir Oblast, Central Federal District, Russia","41.9507874","55.5015040","42.1036030","55.6325263","Q16495368","ru:Городской округ Муром",""`

**Comment by sfkeller** [comment]
Thanks for reporting. That's a problem mainly in the OSM data source.
The water way from Marion County Texas where the error occurs is an obviously nonsense and malicious name tag containing a backslash "\" ! 
I've deleted that name https://www.openstreetmap.org/way/198111246/history . 
So, importing again should resolve that.
Having said this, there's perhaps a sanitizing check needed in OSMNames.

**Comment by chapmanjacobd** [comment]
Ok great! I was able to import it after running into a few snags

`cat planet-latest_geonames.tsv | sed -e 's/[\]//g' > ../Documents/osmnames.csv`

(this also works `sed "s/\\\\//g"`)

then I got this:
```
test=# \copy osmnames from '/home/xk/Documents/osmnames.csv' DELIMITER E'\t';
ERROR:  value too long for type character varying(32767)
CONTEXT:  COPY osmnames, line 14131274, column housenumbers: "1854, 1925, 1884, 1815, 1898, 4472, 1864,1864 BIS, 1916, 1841, 1821, 1896, 4476,4482, 1869,1869 BIS,..."
```

I didn't need housenumbers for my purposes so I did this:

`cut -d' (insert tab character here by pressing ctrl-v and then tab) ' -f1-23 ../Documents/osmnames.csv > ../Documents/osmnames2.csv`

**Comment by philippks** [comment]
> Thanks for reporting. That's a problem mainly in the OSM data source.
> The water way from Marion County Texas where the error occurs is an obviously nonsense and malicious name tag containing a backslash "\" !
> I've deleted that name https://www.openstreetmap.org/way/198111246/history .
> So, importing again should resolve that.
> Having said this, there's perhaps a sanitizing check needed in OSMNames.

@sfkeller 
is it appreciated to remove any backspace from the names? Any other special character which would make sense to be removed?
