### ISSUE TITLE
Venezuela is missing from import

### ISSUE THREAD

**Issue by pablocm** [OSMNames/OSMNames#182]
Hi,
When doing an export using either [South America PBF](https://download.geofabrik.de/south-america-latest.osm.pbf) or [Venezuela PBF](https://download.geofabrik.de/south-america/venezuela-latest.osm.pbf), the resulting TSV is missing Venezuela (OSM ID: [272644](https://www.openstreetmap.org/relation/272644)). I've tried using both the current master branch (#a31e7d29) and the yet unmerged [v2.1](https://github.com/OSMNames/OSMNames/pull/179/commits) with no success. 

Other countries seem to be exported fine. Any ideas on to how to debug this? Thanks.

Attached files:

* Output TSV for Venezuela PBF: [venezuela-latest_geonames.tsv.gz](https://github.com/OSMNames/OSMNames/files/3174336/venezuela-latest_geonames.tsv.gz)
* OSMNames log output: [docker-osmnames-venezuela.log](https://github.com/OSMNames/OSMNames/files/3174342/docker-osmnames-venezuela.log)

**Comment by klokan** [comment]
I see it at: https://osmnames.org/#q=venezuela

"osm_id": "272644",
 "osm_type": "relation",

**Comment by philippks** [comment]
thanks for your feedback @pablocm 

I processed the pbf of Venezuela myself and you're right, the output does not contain a polygon for the OSM ID 272644. Currently I do not have more time to investigate, but I suspect that the imposm import is not importing it from the PBF file (assuming that the relation is contained in the PBF file).

Strangely, the output contains the polygon when processing the whole planet, as @klokan mentioned.

Hopefully, I find some time this week to have a deeper look on the issue. If you're motivated to solve the issue by yourself, I suggest to have a deeper look on the [imposm import](https://github.com/OSMNames/OSMNames/blob/master/osmnames/import_osm/import_osm.py#L43).

**Comment by pablocm** [comment]
Thanks for the response. I've checked it and indeed the problem is that imposm is not importing it from the PBF file.

I did a quick exploration of the PBF file (using osmconvert) and the relation is present inside (with the "boundary:administrative" tag set properly), but it didn't get imported.

I also noticed that neighboring countries are also present inside the PBF file but are not getting imported either, so I guess there's some filtering occuring inside imposm, but I'm not familiar enough with the tools and the PBF format to understand why, yet. I assume this filtering doesn't happen when working with the planet PBF.

**Comment by philippks** [comment]
Alright, I identified the problem.

One can check the integrity of the OSM file with osmium:
```
osmium check-refs -i -r venezuela-latest.osm.pbf
```

The output contains the line: `w245555935 in r272644` which says that the [way 245555935](https://www.openstreetmap.org/way/245555935) is missing from the [relation 272644](https://www.openstreetmap.org/relation/272644).

As quick fix I removed the corresponding relation_member from the OSM file (as described [here](https://help.openstreetmap.org/questions/67783/editing-deleting-nodes-in-osmpbf-file/67784))

After processing the modified OSM file, the output contains the Relation:
[venezuela-latest-modified_geonames.tsv.gz](https://github.com/OSMNames/OSMNames/files/3181761/venezuela-latest-modified_geonames.tsv.gz)

**Comment by mtmail** [comment]
Can you contact geofabrik? That usually means the .poly boundaries need to be updated to include the way/island and then future extracts will work http://download.geofabrik.de/south-america/venezuela.html

**Comment by pablocm** [comment]
I've sent an email to Geofabrik to let them know about the issue. Thanks for the help!
