### ISSUE TITLE
API method for finding place result with osm_id or id

### ISSUE THREAD

**Issue by vahdet** [OSMNames/OSMNames#184]
Is there a [OSMNames API](https://osmnames.org/api/) method for finding a place with given `id` or `osm_id`?

That's why I ask it and my desired use case: Instead of the name of the result, I plan to store one of those properties (`id`, `osm_id`) from the result of **autocomplete API** search. And when I want to retrieve a name corresponding to the id I have, I would like to call a finder API to find the place name for it.

**Comment by philippks** [comment]
hey @vahdet, the webpage and api is actually a different project: https://github.com/klokantech/osmnames-sphinxsearch

could you create an issue there?

**Comment by vahdet** [comment]
I did: https://github.com/klokantech/osmnames-sphinxsearch/issues/65

So, I am closing this issue. Thanks.
