### ISSUE TITLE
Entries missing from release 2.1.1

### ISSUE THREAD

**Issue by misiman** [OSMNames/OSMNames#188]
Hi,

It appears that several valid OpenStreetMap entries are present using the osmnames.org autocomplete search that are not included in planet-latest_geonames.ts.gz. Some examples include:

osm_id 206754 - Woodbridge
osm_id 342786 - Pina de Ebro
osm_id 5732227 - Krummenacker

Is there a logical and/or logistical reason for this?

Regards

**Comment by nilo85** [comment]
Same for Stockholm (Capital of Sweden), osm_id 25929985

**Comment by sfkeller** [comment]
OSMNames.org webpage and search API is actually a different project. 
Could you create an issue there and check there first? 
See https://github.com/klokantech/osmnames-sphinxsearch . 
(Closing this issue here).
