### ISSUE TITLE
Not able to replace the sample data with india.tsv

### ISSUE THREAD

**Issue by sumathicheerla** [OSMNames/OSMNames#194]
Hi
Iam facing the issues while running the 
docker run -d -p 80:80 klokantech/osmnames-sphinxsearch.
it has to come with sample data,but iam not able to get the data.
i run the image by replacing the sample data with india.tsv.
docker run -d --name klokantech-osmnames-sphinxsearch \
    -v /india.tsv:/data/input/india.tsv \
    -p 80:80 \
    klokantech/osmnames-sphinxsearch
still not able to get the complete india places data(whta i see with demo url).

cheers
Sumathi.

**Comment by philippks** [comment]
hi @sumathicheerla, did you create india.tsv as described in the README?

btw. you should create the issue on the repository of osmnames-sphinxsearch (https://github.com/klokantech/osmnames-sphinxsearch)

## Data

The world extract can be downloaded here:
https://github.com/geometalab/OSMNames/releases/download/v2.0/planet-latest_geonames.tsv.gz

https://github.com/geometalab/OSMNames/releases/download/v2.0/planet-latest_housenumbers.tsv.gz


If you want to extract only the information for a specific country, you can use the following command

```
awk -F $'\t' 'BEGIN {OFS = FS}{if (NR!=1) {  if ($16 =="[country_code]")  { print}    } else {print}}' planet-latest.tsv > countryExtract.tsv
```
where country_code is the ISO-3166 2-letter country code.

**Comment by sumathicheerla** [comment]
Hi philippks 
     Thank you for the response.
     yes i created india.tsv and run the docker image.
docker run -d \
    -v /path/to/folder/india.tsv:/data/input/data.tsv \
    -p 80:80 \
    klokantech/osmnames-sphinxsearch
but still not getting complete places.
Thanks
Sumathi.

**Comment by philippks** [comment]
@sumathicheerla what do you mean with:

> but still not getting complete places.

is the data you're searching in the source file `india.tsv`? If no, is it in the full file `planet-latest_geonames.tsv.gz`? Please try to debug the issue by yourself a bit and describe what you tried. It does not seem to be a issue of OSMNames, therefore I close this issue. You can still add comments, but I can't promise to help.

**Comment by sumathicheerla** [comment]
Hi philipp

     I resolved the issue.

 Thank you
Sumathi.
