### ISSUE TITLE
use non-english language as default

### ISSUE THREAD

**Issue by MosheL** [OSMNames/OSMNames#195]
Hi !

I am trying to make a TSV file with an Hebrew names.
I was tried to read the code, the python, connect to the  pg database, etc, and did not found:

How I can change the default names  to Hebrew ?

How I can read the tables from the process? I tried to connect ti pgsql with superuser, but see nothing.

Thanks !

**Comment by sfkeller** [comment]
Hi, 

We're maintaining this software and repo in our spare time and we can't give much support here. I'd like to keep theses issues constrained on bugs and eventually on feature requests. So pls. understand that I'm closing this issue.

There's still a chance to get - and give(!) - community support. For this I'd suggest that you ask your question at Stackoverflow: https://stackoverflow.com/search?q=%5Bopenstreetmap%5D+osmnames .
