### ISSUE TITLE
How add and search by house numbers

### ISSUE THREAD

**Issue by gabrielibis** [OSMNames/OSMNames#196]
I want to search by house number, like in portugueses: "Avenida amazonas, bairro cachoeira, 102". (Street, neighborhood and house number). I need to get the exacly addres of user, I following the steps describeds in [](https://osmnames.org/docs/). But when I Search by house number can't find the addres, just street. Example: I just find "Avenida amazonas, bairro cachoeira".
I'm working with just Brazil database, maybe there is no house numbers. Anyone can help me?

**Comment by philippks** [comment]
hi @gabrielibis you can find the implementation of the web interface and the search in the repository: https://github.com/klokantech/osmnames-sphinxsearch. Unfortunately, the house numbers are not yet implemented, as you see in this issue: https://github.com/klokantech/osmnames-sphinxsearch/issues/43

This repository only generates the data, which is used by the search. The `planet-latest_geonames.tsv.gz` contains the geonames (as countries, cities, streets, ...) and the `planet-latest_housenumbers.tsv.gz` contains the house numbers of the streets.

Therefore, I close this issue.
