### ISSUE TITLE
LOAD DATA INFILE (MySQL)

### ISSUE THREAD

**Issue by Jack8787** [OSMNames/OSMNames#197]
Hello, friend, I'd like to import the 'OSMNames.tsv' into MySQL-table, and after importing I find out that some records is loaded incorrectly (for example, in column 'osm_type'  values of column 'osm_id', ...), may I'm doing all it correctly ,  but have to add some details to request :

LOAD DATA LOCAL INFILE '$curFolder/$filename'
        IGNORE
	INTO TABLE $tbl
	CHARACTER SET 'utf8mb4'
	FIELDS TERMINATED BY '\t'
	LINES TERMINATED BY '\n'
        IGNORE LINES 1;

**Comment by Jack8787** [comment]
For Windows OS at first I used '\r\n' for LINES, and didn't get result(records just haven't been loaded), then I took away '\r'.
Additionally,may I have to add  options:
ENCLOSED BY AND ESCAPED BY (for fields);
  STARTING BY (lines) ?
I wonder if anyone has tried to do the same.

**Comment by Jack8787** [comment]
DROP TABLE IF EXISTS `osm`.`generalData`;
CREATE TABLE `osm`.`generalData` (
 -- `nwrtype` CHAR(1) NOT NULL '',
  `name` VARCHAR(300) NOT NULL DEFAULT '',
 `alternative_names` TEXT,
  `osm_type` VARCHAR(10) NOT NULL DEFAULT '',
  `osm_id` VARCHAR(15) NOT NULL DEFAULT '',
  `class` VARCHAR(25) NOT NULL DEFAULT '',
  `type` VARCHAR(25) NOT NULL DEFAULT '',
  `lon` VARCHAR(25) NOT NULL DEFAULT '',
  `lat` VARCHAR(25) NOT NULL DEFAULT '',
  `place_rank` TINYINT UNSIGNED NOT NULL DEFAULT 0, -- rank from 1-30 ascending depending on the type and class
  `importance` VARCHAR(30) NOT NULL DEFAULT '', -- importance [0.0-1.0] depending on wikipedia if available otherwise just the ranking
  `street` VARCHAR(500) NOT NULL DEFAULT '',
  `city` VARCHAR(200) NOT NULL DEFAULT '',
  `county` VARCHAR(200) NOT NULL DEFAULT '',
  `state` VARCHAR(100) NOT NULL DEFAULT '',
  `country`	VARCHAR(100) NOT NULL DEFAULT '',
  `country_code` CHAR(2) NOT NULL DEFAULT '',	-- ISO-3166 2 letter country code
  `display_name` VARCHAR(500) NOT NULL DEFAULT '',	-- the display name representing the hierarchy
  `west`  VARCHAR(15) NOT NULL DEFAULT '', -- bbox
  `south` VARCHAR(15) NOT NULL DEFAULT '', -- bbox
  `east`	VARCHAR(15) NOT NULL DEFAULT '', -- bbox
  `north`	VARCHAR(15) NOT NULL DEFAULT '', -- bbox
  `wikidata` VARCHAR(15) NOT NULL DEFAULT '', -- the wikidata associated with this feature
  `wikipedia` VARCHAR(50) NOT NULL DEFAULT '', -- the wikipedia URL associated with this feature
  `housenumbers` VARCHAR(500) NOT NULL DEFAULT '' -- the wikipedia URL associated with this feature
  );

**Comment by Jack8787** [comment]
one more question, perhaps the final one: Which version you would tell me to use? It seems  2.1.1 version is made more clearly.

**Comment by sfkeller** [comment]
Hi @Jack8787 : Thanks for using this dataset. This is only a small project so don't expect any (free or immediate) support. 

I'd suggest, you ask your question also to https://stackoverflow.com/search?q=OSMNames since it's rather related to MySQL anyway.

Pls. let me close this for now. We can reopen it in case there's new input.
