### ISSUE TITLE
White page on website?

### ISSUE THREAD

**Issue by rugk** [OSMNames/OSMNames#202]
This is how it looks for me:
![grafik](https://user-images.githubusercontent.com/11966684/105640885-fb4ec380-5e80-11eb-9d56-ae9cfcee15f5.png)

There should be a map, should not it? There is none… however.

Firefox 84

## Problem

The tiles hosting service seems to be down/has changed:
![grafik](https://user-images.githubusercontent.com/11966684/105640937-71532a80-5e81-11eb-88c6-51f3f64c3812.png)

**Comment by philippks** [comment]
The web interface is part of this project: https://github.com/klokantech/osmnames-sphinxsearch

**Comment by rugk** [comment]
Okay, cannot reproduce it anyway, after that lot of time, so I guess it's fine.
