### ISSUE TITLE
Updated download release

### ISSUE THREAD

**Issue by AliFlux** [OSMNames/OSMNames#207]
Hi.

Are there any plans to publish the 2022 data dump? The latest release on the repo is of 2019, and that is about three years old.

I don't have the compute power right now to generate it myself, any help would be appreciated.

Thanks.

**Comment by hholzgra** [comment]
Any news on this?

**Comment by sfkeller** [comment]
@philippks volunteered - but we have to organize computing power ourselves first, as well as man power. Will take about a month I guess.

**Comment by philippks** [comment]
Short status update: I didn't succeed yet to run the export for the full planet, because of performance reasons (the exports just never finished...). I'll try to find the bottlenecks and / or tune the postgres configuration.

**Comment by philippks** [comment]
Status update: I created a new pre-release with the latest export: https://github.com/OSMNames/OSMNames/releases/tag/v2.2.0-rc1

I shortly verified the output and it looks ok. However, I didn't find the time to verify in detail. Maybe someone can support me with this?

**Comment by hholzgra** [comment]
I'll give it a try tomorrow ...

**Comment by hholzgra** [comment]
Only got to it today, but I can confirm that the new dump works fine for me

**Comment by philippks** [comment]
thanks for testing the release @hholzgra
