### ISSUE TITLE
Is that a mistake in the yaml file?

### ISSUE THREAD

**Issue by dagnelies** [OSMNames/OSMNames#213]
https://github.com/OSMNames/OSMNames/blob/bb8c4bb9ee32318e18de64081f4839f231558356/osmnames/import_osm/mapping.yml#L73

**Comment by philippks** [comment]
Seems to be a valid key for the country code, no? https://wiki.openstreetmap.org/wiki/Country_code

**Comment by dagnelies** [comment]
I meant because of the duplicate key "key" in the object. 

    - key: country_code
      name: imported_country_code
      type: string
      key: ISO3166-1:alpha2   <<<<< 
    - key: name:en

**Comment by philippks** [comment]
Ah yes, you're right. This seems like a leftover... I fixed it here: https://github.com/OSMNames/OSMNames/pull/224
