### ISSUE TITLE
Place Name Not Found 

### ISSUE THREAD

**Issue by 5212BABA** [OSMNames/OSMNames#235]
Hello Why when I typed the name of my village tomba Kanssa, it doesn't appear in the list of search results osmnames here is the output of openstretmap nomination request https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=15962609&class=boundary&keywords=1&addressdetails=1&hierarchy=0&group_hierarchy=1&format=json

**Comment by sfkeller** [comment]
Hi, thanks for reporting.

This is the wrong place to ask such questions for several reasons: 
1. This is a database, not a search engine. Yout probably used https://osmnames.org/ which has it's own issue tracker. 
2. We unfortunately can't give support here: See https://github.com/OSMNames/OSMNames/blob/master/README.md#support

**Comment by mtmail** [comment]
https://osmnames.org/ has a link to this github repository in the header, in the footer ("OSMNames project is maintained by the OSM community (https://github.com/osmnames/osmnames/) [...]" and on the documentation page https://osmnames.org/docs/ ("Feel free to submit an issue (https://github.com/osmnames/osmnames/issues) if you think something is missing or does not run as it should."

If there's a better place to ask the question then I'd be good to update the links.

**Comment by 5212BABA** [comment]
Thank you so much for the help and quick response to my concerns I will try created another issue on OSM names.
