### ISSUE TITLE
Attach bbox larger than a point to all entities

### ISSUE THREAD

**Issue by sfkeller** [OSMNames/OSMNames#45]
Currently not all entities have a 'real' bbox which: Those e.g. coming from a node have zero extent. Try to attach a realistic bbox by estimating/guessing. E.g. by deriving bbox from extent of enclosing entity, or guessing some 100 meters if it's of type "village". 
Other ideas?

**Comment by klokan** [comment]
If the original data does not have bbox - then the OSMNames should not have it either (degraded to a point). The application using the data should decide how to handle it.

Our search system (http://osmnames.klokantech.com/), while zooming map to the search result is doing similar approximation already.

**Comment by sfkeller** [comment]
Ok for the guessing part. But I think, there's more in the original data to be derived, like e.g. the centroid from the enclosing polygon of same name.

**Comment by klokan** [comment]
Improving the quality of the bbox (or deriving missing bbox from another related OSM data) would be great indeed.

To turn this ticket into action - exact examples should be provided - for "how" to make this exactly.

It is also true the lat/lon in the export is now quite dummy - and can be calculated in a more clever way (label placement, centroid of polygon, related OSM entity for label, etc.). I think it is now maxx-minx, maxy-miny of the bbox (but maybe @and01 made it more clever?).

**Comment by philippks** [comment]
I close this issue for now. I think new issues with concrete examples are more efficient.
