### ISSUE TITLE
Water bodies and mountains/hills/islands/deserts

### ISSUE THREAD

**Issue by sfkeller** [OSMNames/OSMNames#48]
Geo names (toponyms - the study of place names) include bodies of water and mountains/hills. E.g. Matterhorn or Zürichsee.

**Comment by klokan** [comment]
+1

**Comment by klokan** [comment]
Name of islands, deserts ("Sahara"), would be great to have as well, etc.

@sfkeller when will the new student start? Shall we discuss the priorities - or agree on a kick-off meeting?

**Comment by sfkeller** [comment]
I'd like to define a complete list of toponyms OSMNames:
See https://github.com/OSMNames/OSMNames/wiki

**Comment by klokan** [comment]
Grep `- name: name` on all mapping.yaml in in OpenMapTiles repo gives you 6 layers.

See:
https://github.com/openmaptiles/openmaptiles/search?utf8=%E2%9C%93&q=%22name%3A+name%22+filename%3Amapping.yaml&type=Code

**Comment by klokan** [comment]
This is where it would make sense to reuse OpenMapTiles, if fact.

**Comment by simran001** [comment]
**1. Added the following tags:**
* river
* riverbank
* stream
* canal
* drain
* ditch
* mountain_range
* island
* reservoir
* water
* bay
* desert
* ocean
* sea
* continent
* country
* state
* peak
* volcano
* hill

Also see the [wiki](https://github.com/OSMNames/OSMNames/wiki).
