### ISSUE TITLE
Indexing house numbers and zip in the street record

### ISSUE THREAD

**Issue by klokan** [OSMNames/OSMNames#49]
For fulltext search it would make sense to have in the TSV dump a field with "house_numbers" - listing all house numbers, and also the "zip" code.

This way the fulltext search would be able to verify an address is correct and provide directly a record for a street as a result.
On the search server could be external logic for parsing addresses - making lookup for LonLat of the individual house for give street - in an external non-fulltext database.

During indexing as well as during searching a library for parsing & normalizing address would be helpful - to cover variety of formatting and alternatives for how people write an address.
Something like `libpostal` described in [libpostal-overview](https://github.com/geometalab/OSMNames/wiki/libpostal-overview) - (tested and not-yet-used in production for now, see: https://github.com/klokantech/osmnames-sphinxsearch/issues/9)

This may be a solution how to extend the OSMNames search to support postal address search as well - with an acceptable quality and performance.

**Comment by klokan** [comment]
If export of addresses is done into external TSV - as suggested in #14 - we would need only an identifier of a street object to be present there - to enrich the fulltext index appropriately.
The original TSV with places would not need to contain list of these values then.

**Comment by sfkeller** [comment]
House numbers (= building addresses) are a topic in itself. I'm personally very keen to have such a building address database but IMHO they should no be mixed with a geo name data bases (toponyms) like OSMNames, which should remain "coarse grained" as opposite to "fine grained" (name encoding). This is why there's a separate label and why the thesis shows the "L" graphics to illustrate this.

**Comment by sfkeller** [comment]
Zip codes are no relyable data in OSM and in principl. They are typically derived from internal postal usage as non official polygons and many countries have no Zip available.

**Comment by klokan** [comment]
Is the thesis PDF published online? I know only of documentation - which is now available (also as PDF and ePub under: http://osmnames.readthedocs.io/en/latest/

**Comment by sfkeller** [comment]
@klokan Are you still interested in this full text feature?

**Comment by klokan** [comment]
Yes, please.
Otherwise we have not way how to validate an address directly from the fulltext search index.

**Comment by sfkeller** [comment]
Given the separate housenumbers data set we have a normalized many to one relationsship and there are many fields. When we would introduce such a "house_numbers" in the main file we would get a partial redundancy. 
In any case, any consumer of the two files (like the Sphinx indexer) can generate such a field on his side.
So, I'm reluctant to add such a field in th main file (I'm still open to discuss this also bilaterally).

**Comment by klokan** [comment]
Does not have to be directly included - but a utility which is creating new TSV with this extra column needs to be implemented if the full text search should validate the available house numbers and get a correct osm-id for a road in an address query.

Can you implement such utility?

SphinxSearch would require TSV produced by the utility - not the one which people download from the release directly - which will make it confusing. Maybe the utility would need to be integrated into sphinxsearch docker. It is just additional time consuming step during indexing - which must validate all relation and merge the two TSV data correctly.

**Comment by klokan** [comment]
Maybe the implementation in sphinx search can do the validation on top of SQLite - not on top of the   fulltext search index - but it would be slower - or not possible an all candidates.

It means every sphinxsearch query is more expensive - and street + zip query such as "Bahnhofstrasse, 6314" identifying street in a town will not be possible - or will not give the result.

Similarly a house number or very popular streetname would need to scan a lot of different house records for all candidate streets in SQLite. I belive performance would be degraded.

Usage of libpostal brings another troubles (such as additional RAM required on the server) - and it does not solve the validation - only identification of the house number in the query.

**Comment by philippks** [comment]
House numberes are now exported to housenumbers.tsv and into a new column in geonames.tsv. Documentation about the new column will follow.

merged with PR #124
