### ISSUE TITLE
Release TSV data to be sorted

### ISSUE THREAD

**Issue by klokan** [OSMNames/OSMNames#51]
The release data should be sorted by the rank automatically.

Please sort and replace the data in 1.1 release @MartinMikita

**Comment by MartinMikita** [comment]
Data were sorted:
```
$ time gawk -F"\t" -v OFS='\t' 'NR>1 {print$0}' planet-latest.tsv | sort -T `pwd`/tmp -t $'\t' -k 10 -nr > planet-sorted.tsv
  
real	10m41.120s
user	6m25.348s
sys	3m30.973s
```

Sorted data are now available as https://github.com/OSMNames/OSMNames/releases/download/v1.1/planet-latest.tsv.gz

Original data were just renamed to https://github.com/OSMNames/OSMNames/releases/download/v1.1/planet-latest-orig.tsv.gz
But we can delete it.
