### ISSUE TITLE
Add LICENSE file (or readme section)

### ISSUE THREAD

**Issue by mtmail** [OSMNames/OSMNames#52]
I'm sure the repository is under a open licence. But which one? And which of the data files are public domain/open licence/odbl (derived).
Thanks!
(Sitting at SotM Brussels talk)

**Comment by klokan** [comment]
@sfkeller please clarify the decision from the side of the university.

I am strongly in favor of MIT - equal to https://github.com/osm2vectortiles/osm2vectortiles/blob/master/LICENSE

ODBL license applies to the generated data we distribute (linked from the /download/ section of the website).

KlokanTech source code (the search engine [osmnames-sphinxsearch](https://github.com/klokantech/osmnames-sphinxsearch) software as well as the JavaScript [Autocomplete component](https://github.com/klokantech/javascript) has LICENSE file already.

**Comment by sfkeller** [comment]
My default license is MIT - and I'd like to confirm that this is MIT here too. 
I'm on the way to Brussels (:-)) so if someboy has more time pls. add it - or I'll do it next few days.

**Comment by sfkeller** [comment]
The license MIT was chosen before code was added. Now - after first release - it's obvious that it must be changed to GPL (inc. attribution og Nominatim) since SQL code was taken from Nominatim!

**Comment by klokan** [comment]
GPL v2 license is now in the repo. I was not aware the students copied the SQL code directly.

Improving the attribution / copyright notices further is welcome - especially if somebody makes a pull request...
