### ISSUE TITLE
Complete (extract/deduplicate) housenumber and street names

### ISSUE THREAD

**Issue by sfkeller** [OSMNames/OSMNames#60]
One of the main tasks of the OSMNames building addresses project is to complete housenumber and street name for a given building. These are some situations in the OSM data:
* street-name is wrong (i.e. no street existing nearby with this name). (e.g. [this](http://www.openstreetmap.org/node/356431217))
* street-name is missing (and addr:place too).
* node coordinates are outside a building polygon.
* (more?)

It's worth to include nearby streets and e.g. POIs (which could contain addr info) in order to complete missing or correct wrong information.

**Comment by sfkeller** [comment]
> street-name is missing (and addr:place too).
is covered by #14

**Comment by philippks** [comment]
I created another issues to handle wrong street names: #107 

I propose to close this issue and create new issues with specific examples if we see one.

**Comment by sfkeller** [comment]
Yes. You can close it.
