### ISSUE TITLE
When parsing the TSV file line-by-line, I get an inconsistent number of fields

### ISSUE THREAD

**Issue by umpc** [OSMNames/OSMNames#64]
Hello,

I have downloaded the latest release file: https://github.com/OSMNames/OSMNames/releases/download/v1.1/planet-latest.tsv.gz

When trying to read that file line-by-line and parse its lines into typed objects with analogous fields to the TSV file, some lines appear to have an alternating number of fields, so parsing fails as soon as it tries to parse a string such as "node" or "place" as a float or integer in my program.

Since the correct name of a field can only be selected by using the amount of total fields in the line and the array index position, I am unsure of how to correctly use the file. Perhaps it is a naivety of the CSV library I am using and the ones I have already tried.

I have used Go's ```encoding/csv``` package, but also wrote my own brief implementation using ```bufio.Scanner``` to check against, which has the same issue.

My buffered reader, ```csv.Reader```, has the following options set:
```
csvReader := csv.NewReader(osmNamesFile)
csvReader.FieldsPerRecord = -1
csvReader.LazyQuotes = true
csvReader.TrimLeadingSpace = false
csvReader.Comma, _ = utf8.DecodeRuneInString("\t")
```

Reading line-by-line like this, where ```column``` is a hash table of index integers for the desired column, and the ```row``` value being returned is an array of strings (column values):
```
for i := 0;; i++ {
	    if row, err := csvReader.Read(); err == io.EOF {
	        break
	    } else if err != nil {
	        log.Fatal(err)
	    } else {
		    if i == 0 {
			    continue
		    }
		    place := OSMObject{}

		    if len(row) > column["name"] && row[column["name"]] != "" {
			    place.Name = row[column["name"]]
		    }
		    if len(row) > column["alternative_names"] && row[column["alternative_names"]] != "" {
			    place.AlternativeNames = row[column["alternative_names"]]
		    }
		    if len(row) > column["osm_type"] && row[column["osm_type"]] != "" {
			    place.OSMType = row[column["osm_type"]]
		    }
		    if len(row) > column["osm_id"] && row[column["osm_id"]] != "" {
			    osmID, err := strconv.Atoi(row[column["osm_id"]])
			    if err != nil {
				    log.Fatal(err)
			    }
			    place.OSMID = int64(osmID)
		    }
	    	    ...
	    }
}
```

This manual loop and checks were written after trying to use the automatic CSV parser here: https://github.com/gocarina/gocsv but I ran into the same issue as the above two approaches.

I am hoping that this is an issue with Go's CSV parser. Any help at all, or confirmation of this working in other languages/programs other than sphinx would be greatly appreciated!

Thank you.

**Comment by MartinMikita** [comment]
Hello,

Thanks for your message.
But this is a known and reported bug, see #44
The only workaround for this problem is to check the number of columns and skip them now.

This ticket is duplicate. Closing.
