### ISSUE TITLE
import-osm docker has several errors: unable to find imposm3 and invalid character in mapping file

### ISSUE THREAD

**Issue by hpfast** [OSMNames/OSMNames#65]
Hi, I'm getting stuck with quite a few errors running `docker-compose run import-osm` with a custom pbf file (it's a small file of one town in the Netherlands).

The first error was that the go get step to install imposm3 seemed not to be doing anything. When I ran the container, import-osm.sh complained that imposm3 could not be found. I worked around this by downloading the latest binary directly from https://imposm.org/static/rel/

The next problem was that it wouldn't recognize the -dbschema-import tag (in import-osm.sh), though that might be because I changed the imposm3 installation?

```
 docker-compose run import-osm                                                                                                       
Starting osmnames_cache_1
Starting osmnames_pgdata_1
flag provided but not defined: -dbschema-import
Usage: /imposm3/imposm3 import [args]

  -appendcache=false: append cache
  [truncated]
```

 I removed this tag, not being able to find any documentation on it. imposm3 then would run.

The final problem which has stumped me is the error message:

```
$ docker-compose run import-osm  
Starting osmnames_cache_1
Starting osmnames_pgdata_1
[Mar 15 18:09:02] mapping file: invalid character 'a' in literal true (expecting 'r')
```

I fiddled around with the mapping.yaml and related environment variables but didn't really know what I was doing so don't think I'm making much headway ...

Is any of this known? If you have time, any help would be appreciated.

**Comment by sfkeller** [comment]
Did you use the docker files from master committed around 9.3.2017?

**Comment by hpfast** [comment]
yes, I have commit #e20488c0ab

**Comment by philippks** [comment]
Hello @hpfast 

I did some work for OSMNames recently. You can find my current progress here: https://github.com/philippks/OSMNames

The readme isn't yet up to date, but you can clone the repo and execute following commands:
```
docker-compose build
# (optionally update src/download-pbf/download-pbf.sh to your file and / or put the pbf manually in the data/import directory)
docker-compose run osmnames
``` 

It's not yet possible to execute only one step of the process, but you can comment out a command in the file `src/run.sh` if you want to skip any.

**Comment by hpfast** [comment]
thanks @philippks, I'll check it out later today.

**Comment by hpfast** [comment]
@philippks your fork works just great, thanks.

**Comment by hpfast** [comment]
Feel free to close this issue if it isn't useful at the moment!

**Comment by sfkeller** [comment]
@philippks: Can you pull and merge your fork to master, so that other's aren't trapped too?
