### ISSUE TITLE
City of Lake of Zurich set to Lake of Zurich

### ISSUE THREAD

**Issue by philippks** [OSMNames/OSMNames#73]
In the tsv output is the city attribute of the Lake of Zurich set to "Lake of Zurich". This is wrong.

This is because all polygons with the place_rank between 16 and 20 are considered to be the city:
https://github.com/OSMNames/OSMNames/blob/master/osmnames/export_osmnames/functions.sql#L72

but the place_rank for water (and deserts) are set to 16:
https://github.com/OSMNames/OSMNames/blob/master/osmnames/import_osm/set_place_ranks.sql#L13

We've to rethink the concept about setting the place_rank when importing and depending on the place_rank when getting information from parent polygons.

**Comment by simran001** [comment]
Solved with PR #82
