### ISSUE TITLE
do not set country_code for all elements

### ISSUE THREAD

**Issue by philippks** [OSMNames/OSMNames#88]
Right now we're setting the country_code for all the elements:
* linestrings
* points
* polygons
* housenumbers

In the export is the country_code used to get the correct country.

But since we're creating a hierarchy of all elements we could determine the country from it (right now only city, county and state are determined by the parents). If we would extend the [method get_parent_info](https://github.com/OSMNames/OSMNames/blob/master/osmnames/export_osmnames/functions.sql#L47) to return the country too, we could remove the redundant step of setting the country_code for all elements but only set it for the relevant polygons (countries).

**Comment by sfkeller** [comment]
Yes, refactoring is clean code and good :-)
