### ISSUE TITLE
Wrong boundingbox when crossing dateline?

### ISSUE THREAD

**Issue by sfkeller** [OSMNames/OSMNames#94]
@klokan wrote in #57 :
>  There is something wrong with the bounds (switched order delivered from server?)
>  When I try the tool: http://boundingbox.klokantech.com/
>  when searching Google Maps gazetteer - it displays the bounds correctly - 
>  but when searching OSMNames - there is an issue...

**Comment by das-g** [comment]
The naive approach for determining a (multi-)geography's bounding box (min and max of longitude and latitude of WGS84 coordinates) leads to unintuitive (and not-so-useful) results for geographies containing or intersecting the antimeridian, but also for geographies close to the antimeridian with parts "on both sides" of the antimeridian but not touching it, like New Zealand ([eastern part](http://www.openstreetmap.org/relation/556706#map=5/-40.480/180.000), [western part](http://www.openstreetmap.org/relation/556706#map=5/-40.480/-180.000)). It's clear that to come up with the "correct" bounding box, we cannot look at the world as a rectangular flat map, but must take into account that earth is (approximatively) a sphere.

Unfortunately, PostGIS (nor I guess other GIS tools and libraries) does not (yet?) have bounding box function applicable to geographies. ([`Box2D(...)`](http://postgis.net/docs/manual-2.1/Box2D.html) only works for geometries.)  Thus, we have to make reasonable decisions of our own.

So what is (to us) an (axis aligned) "bounding box" on a sphere? An area that will project to a rectangle in Web Mercator (i.e. an area between two meridians and two parallels) that completely covers the geography in question.

And which is the "correct" bounding box for a given geography? I'd say, it's the area fulfilling the above properties with minimal surface area. (Whether measured on the sphere or on the Web Mercator projection doesn't make a difference for which one is the minimal, if I'm not mistaken.)

How can we find that "correct bounding box" for a given geography? As long as no geography has both, the 0-meridian and the antimeridian in their "correct" bounding box, we can do this by simply calculating two bounding boxes and then taking the smaller one:

- naively calculate the bounding box on WGS84
- naively calculate the bounding box on a "modified" WGS84, where 360° has been added to all negative longitudes. This modification is exactly what [`ST_Shift_Longitude`](http://postgis.net/docs/manual-2.1/ST_Shift_Longitude.html) does, so apply that before determining the "naive" bounding box.

**Comment by das-g** [comment]
Oh, and in case we have to get the result back to the [-180, 180] range: [Is there an inverse operation to ST_Shift_Longitude in PostGIS < 2.3?](https://gis.stackexchange.com/q/242308/51574) (Yes, [there is](https://gis.stackexchange.com/a/242322/51574), but it isn't exactly obvious.)

**Comment by philippks** [comment]
closed with #126 

credit goes to @simran001
